#!/usr/bin/env python3
"""
生成 MySQL 导入 SQL 脚本
"""
import sqlite3
import json
import os
import sys

def generate_sql():
    db_path = os.path.join(os.path.dirname(__file__), 'dms.db')
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    # 获取所有表
    cur.execute("SELECT name FROM sqlite_master WHERE type='table'")
    tables = [row[0] for row in cur.fetchall() if row[0] != 'sqlite_sequence']

    sql_lines = ["-- SQLite to MySQL Migration SQL Script", "-- Generated by export_sqlite.py", ""]
    sql_lines.append("SET NAMES utf8mb4;")
    sql_lines.append("SET FOREIGN_KEY_CHECKS = 0;")
    sql_lines.append("")

    for table in tables:
        cur.execute(f"SELECT * FROM {table}")
        rows = cur.fetchall()
        if not rows:
            continue

        for row in rows:
            row_dict = dict(row)
            fields = []
            values = []
            for key, value in row_dict.items():
                if key == 'sqlite_sequence':
                    continue
                fields.append(f"`{key}`")
                if value is None:
                    values.append("NULL")
                elif isinstance(value, int):
                    values.append(str(value))
                elif isinstance(value, float):
                    values.append(str(value))
                else:
                    # 转义特殊字符
                    escaped = str(value).replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n").replace("\r", "\\r")
                    values.append(f"'{escaped}'")

            sql = f"INSERT INTO `{table}` ({', '.join(fields)}) VALUES ({', '.join(values)});"
            sql_lines.append(sql)

    conn.close()

    sql_path = os.path.join(os.path.dirname(__file__), 'migrate_to_mysql.sql')
    with open(sql_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(sql_lines))

    print(f"SQL 文件已生成: {sql_path}")
    print(f"文件大小: {os.path.getsize(sql_path)} bytes")

if __name__ == '__main__':
    generate_sql()
